version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb_api_pokemon
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb:/var/lib/mysql
    restart:
      always

volumes:
  mariadb:
